### ISSUE TITLE
Schedule - IMPROVEMENT: Calendar events contain web URL be nice if they linked to app instead

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#1]
When you add a Calendar event from the Schedule it includes a web url. Any (easy) way to deep link that back to app instead?

**Comment by challfry** [comment]
Making http:// links open in Kraken is probably not possible in this case, as we'd have to install a file on the server and the app would need to talk to both Apple and the server to enable the links.

So, I've added app links with a custom URL scheme. However, the app links are appended to the event description--the URL is still a link to the web page for the event.

The app links use "kraken://" as their custom URL scheme.
