### ISSUE TITLE
Forum - Image switch animation seems wonky

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#12]
See video. The animation seems strange, better without animation? 

https://drive.google.com/file/d/1EWyvRbqMgUoXclzTMbukPpDz4Tt35Bx9/view?usp=sharing

**Comment by challfry** [comment]
So, those animations look great on iOS 13. I may just disable them for iOS 12.

**Comment by challfry** [comment]
I mean, *I* think they look great. They certainly don't look like the video.

**Comment by challfry** [comment]
Min version is now 15.0, rendering poor animation rendering in iOS 12 moot.
