### ISSUE TITLE
Schedule - With no network Schedule still shows Loading Events spinner

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#18]
See screen shot. With Settings>Block all network traffic enabled, entering Schedule shows the spinner, never dismisses 

<img width="484" alt="Screen Shot 2020-01-25 at 4 29 47 PM" src="https://user-images.githubusercontent.com/1618900/73129061-22ce3000-3f90-11ea-99c7-92c0bd08448e.png">

**Comment by challfry** [comment]
Fixed.
