### ISSUE TITLE
Schedule - APP CRASH: App crashes after deleting Saved Event

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#2]
`2020-01-24 21:22:38.109705-0800 Kraken[75054:1527009] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 1.  The number of items contained in an existing section after the update (2) must be equal to the number of items contained in that section before the update (1), plus or minus the number of items inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ab3a8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001094ddac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ab3a662 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000108f2b76b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x0000000116f6a7f1 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 16127
	5   UIKitCore                           0x0000000116f72f24 -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 71
	6   UIKitCore                           0x0000000116f73267 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 434
	7   UIKitCore                           0x0000000116f73092 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 90
	8   UIKitCore                           0x0000000116f73015 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 74
	9   UIKitCore                           0x0000000116f72f6a -[UICollectionView performBatchUpdates:completion:] + 53
	10  Kraken                              0x0000000107c4dfce $s6Kraken0A10DataSourceC17privateRunUpdates33_984F54868F6C2C97C214A7019EAC9F4ELLyyF + 1358
	11  Kraken                              0x0000000107c4d9bb $s6Kraken0A10DataSourceC10runUpdatesyyFyycfU_ + 27
	12  Kraken                              0x0000000107c11bed $sIeg_IeyB_TR + 45
	13  libdispatch.dylib                   0x0000000111644d7f _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x0000000111645db5 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x0000000111653080 _dispatch_main_queue_callback_4CF + 1540
	16  CoreFoundation                      0x000000010aaa1a79 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x000000010aa9c126 __CFRunLoopRun + 2310
	18  CoreFoundation                      0x000000010aa9b4d2 CFRunLoopRunSpecific + 626
	19  GraphicsServices                    0x0000000110a582fe GSEventRunModal + 65
	20  UIKitCore                           0x00000001176d8fc2 UIApplicationMain + 140
	21  Kraken                              0x0000000107e27a6b main + 75
	22  libdyld.dylib                       0x00000001116ba541 start + 1
	23  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

Steps:
Schedule
Tap on an event>Add to Calendar
Return to app
Go back to Calendar and delete the event
Return to app tap in the Schedule (different event)>Crash KrakenDataSource line 336?

You have to delete app in order to stop the app crashing every time you enter Schedule after initial boom

**Comment by challfry** [comment]
The Calendar's UICollectionView is complaining about an update that had the wrong number of events in a section. I *think* we were getting updates from CoreData that the item at index 0 had moved ... to index 0. UICollectionView doesn't appear to like hearing about these non-moves.
