### ISSUE TITLE
APP iPad Today not showing in portrait 

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#21]
Today screen does not render when device is in portrait mode

**Comment by challfry** [comment]
UICollectionViewFlowLayout would complain if any cells in the CV were wider than the CV itself. When that happened it would refuse to add the cells to the view. Rotating the iPad is one of the things that could cause the CV to take on a different width, and cause this bug to happen.

The best part is that the FlowLayout was about to re-layout everything, and it throws errors and refuses to add cells *before* it tries laying out the cells in the new view (the cells will resize during layout to match the CV width).

Anyway, all the collectionViews now use a custom layout object, which seems to fix this.
