### ISSUE TITLE
APP iPad Twitarr Images scaled to large 

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#22]
In landscape, images are scaling end-to-end L-R. The image is cropped a ton 

![IMG_0012](https://user-images.githubusercontent.com/1618900/73232507-53e96480-4138-11ea-91f7-c943adc4a961.PNG)

**Comment by challfry** [comment]
Fixed by going multicolumn. Those image views are capped at ~250 pix when not selected. With column widths between 350-500px, the constrained height should look okay, while still leaving the stream readable.
