### ISSUE TITLE
APP iPad Twitarr Selected Image view has a share icon which crashes app

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#24]
In Twitarr, a Selected Image view has a share icon which crashes app. Guessing it shouldn't have the icon

![IMG_0014](https://user-images.githubusercontent.com/1618900/73232750-25b85480-4139-11ea-9137-1436cd5e73e4.PNG)

**Comment by challfry** [comment]
On iPad, the share activity wants to be presented as a popover, which means it needs special sauce in order to work. 

(I've added the sauce now).
