### ISSUE TITLE
APP Settings Pending tasks view is kind of a mess

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#27]
See screen shot. Additionally the Cancel in the Status cell (?? yellow) is not functional

![IMG_1065](https://user-images.githubusercontent.com/1618900/73233673-1555a900-413c-11ea-90cd-fb75d63c1422.PNG)

**Comment by challfry** [comment]
Man. That's some good coding right there.

**Comment by challfry** [comment]
Fixed now. Cancel button is hidden for this cell (there's still a cell below it, with cancel/edit buttons that work), the Status: field says "Server Error", and the error field is laid out correctly.
