### ISSUE TITLE
Schedule - Login view navBar is not tappable

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#3]
See screen shot. The Cancel button is not tappable on the login view.

Steps:
Open app without being logged in
Go to Schedule>Any event>Follow
Try to tap Cancel button in upper left corner

<img width="526" alt="Screen Shot 2020-01-25 at 1 44 47 PM" src="https://user-images.githubusercontent.com/1618900/73127714-7da85d00-3f79-11ea-9cd0-d4f101e351f7.png">

**Comment by eegraf** [comment]
NOTE this is log in view FROM Schedule!!

**Comment by challfry** [comment]
That view comes up as a modal. I'm guessing it works on iOS 13 with their new sheet-stack modal UI, but for iOS 12 I need to do something different.

**Comment by eegraf** [comment]
Yep

<img width="300" alt="Screen Shot 2020-01-26 at 8 20 59 PM" src="https://user-images.githubusercontent.com/1618900/73150102-6b154d00-4079-11ea-94dd-dbd06b486297.png">

**Comment by challfry** [comment]
Should be fixed in iOS 12 now. Should still be a pageStack in iOS 13 and fullscreen in iOS 12, but should layout the header bar correctly now.
