### ISSUE TITLE
APP iPad Weird layout for newly created Forum

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#32]
Only iPad, see screen shot. 2 issues: One the new forums are forcing the older ones to be moved to the right. And second the latest forum is shown to have been created 50 years ago. Sometimes that reverts to a more reasonable time, sometimes it doesn't. Backgrounding and returning fixes.

![IMG_1068](https://user-images.githubusercontent.com/1618900/73417251-4c5ac480-42cc-11ea-8e36-6d114c3cc20c.jpg)

**Comment by eegraf** [comment]
not screen shot, this video:
https://drive.google.com/file/d/13K7H5sU5tRUSTUarmeLixwQUWD_p8lgW/view?usp=sharing

**Comment by challfry** [comment]
So, forums are sorted by last post time. There's 2 calls to get info on forums, one of which gets overview data on lots of forums and returns the postTime of the last post of each (but doesn't return individual posts), and one that gets posts in a particular forum and does not tell you the postTime of the last post. 

But! If the latter call gets all the posts in the forum, the last post time should be the timestamp of the last post in the response. Added code to set the forum's lastPostTime in this case.
