### ISSUE TITLE
APP Camera Viewfinder style ON Image is not full screen without hat

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#33]
When a user sets Camera Viewfinder style ON and takes an image in Landscape the taken image is square and doesn't fit screen 

![IMG_1069](https://user-images.githubusercontent.com/1618900/73418634-28e64880-42d1-11ea-91c0-427a9b12e23b.PNG)

**Comment by eegraf** [comment]
So this is on all photos without hats

**Comment by challfry** [comment]
Fixed.
