### ISSUE TITLE
Schedule - IMPROVEMENT: If user Declines Calendar access, there is no subsequent direction how to change mind

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#4]
In Schedule, the first time someone tries to add an event to the Calendar they are prompted to accept that access. If they decline (and since they must choose SOMETHING in the alert in order to dismiss it some might) the next time they tap Add To Calendar nothing happens. There could/should be some instruction about going to settings and allowing access

**Comment by challfry** [comment]
Added an alert; tells the user the can reenable calendar access in Settings.
