### ISSUE TITLE
APP Camera Screen share icon is in the upper left corner and seems to do nothing 

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#41]
![File](https://user-images.githubusercontent.com/1618900/73626601-5ea36e00-45fe-11ea-80ee-338ccd155b6b.jpg)

**Comment by challfry** [comment]
The way you use the hardware volume button to take camera pictures is *still* super janky--you set up an audio session and observe changes to the output audio volume. You also have to build a custom volume view (which Apple allows) and make not show up onscreen (which my code wasn't quite doing).

Anyway, should be fixed now.
