### ISSUE TITLE
Rejected task notification difficult to dismiss

### ISSUE THREAD

**Issue by cohoe** [challfry/TheKraken#63]
When something queues and gets rejected, it appears in the To Be Posted section of Settings and the Today notification badge appears with a count. But none of the sections in Today (Settings, Twitarr, Forums, Seamail, etc) indicate which one has the notification needing addressed. I think some sort of badge or indicator next to the section should be added to guide the user to the place they need to go.

**Comment by challfry** [comment]
Today badge now displays number pending ops (actually total of Announcements + ops), and Settings cell in the Daily view now indicates # of pending ops.
