### ISSUE TITLE
"Last Refreshed" blank in forum view

### ISSUE THREAD

**Issue by cohoe** [challfry/TheKraken#66]
On the forum categories page the "last refreshed" field has a value of some number of minutes and a button to refresh now. When viewing a particular thread all I see is the button to refresh now, not the time since. ![image](https://user-images.githubusercontent.com/505621/218176853-a4b96053-a862-417b-8878-5bc5eebde230.png)

**Comment by challfry** [comment]
Fixed now. The cell wasn't being told when refreshes happened.
