### ISSUE TITLE
Schedule: Scrolling is wonky

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#7]
May just be in Sim, not sure yet... but user cannot scroll as expected. It SEEMS like the only time you get a handle to scroll is when you are in an active cell?

**Comment by challfry** [comment]
I have a UILongPressGestureRecognizer running in some collection views, to make cell selection work better. It wasn't playing as nicely with the UIScrollView's pan gesture recognizer as I might like. Should work better now.
