### ISSUE TITLE
Inconsistent presentation of log in view

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#8]
When a user is not logged in and attempts to access features requiring login, they are presented with the log in screen. This can happen from nearly every spoke (Twittar, Forums, Seamail etc). Some of these screens have navBars, others do not, some show the tab bar, others do not. 
<img width="300" alt="Scrapbook" src="https://user-images.githubusercontent.com/1618900/73128181-78024580-3f80-11ea-945b-51704612c512.png">
<img width="300" alt="Schedule" src="https://user-images.githubusercontent.com/1618900/73128182-78024580-3f80-11ea-8f00-6cbbf129254d.png">
<img width="300" alt="Twittar - Reply Post" src="https://user-images.githubusercontent.com/1618900/73128183-78024580-3f80-11ea-801a-51e4836436ae.png">
<img width="300" alt="Forums - New" src="https://user-images.githubusercontent.com/1618900/73128184-78024580-3f80-11ea-95e2-edeba46caa2d.png">
<img width="300" alt="Twittar- LIke" src="https://user-images.githubusercontent.com/1618900/73128185-78024580-3f80-11ea-9881-b6afa56cbf75.png">
<img width="300" alt="Forums - Post" src="https://user-images.githubusercontent.com/1618900/73128186-78024580-3f80-11ea-9703-1198e4ff3718.png">
<img width="300" alt="Seamail" src="https://user-images.githubusercontent.com/1618900/73128187-78024580-3f80-11ea-8e11-c0d17d2ac681.png">

**Comment by challfry** [comment]
They all have navbars, but some of them are getting covered up by the notch and the status area. Should be fixed now (the bars should always be below the status area).
