### ISSUE TITLE
Implement X-Swiftarr-Client and X-Swiftarr-User Headers

### ISSUE THREAD

**Issue by cohoe** [challfry/TheKraken#82]
To enable us to debug troublesome clients and get more insights on what clients people use, I've established two HTTP headers in Swiftarr and Tricordarr:

`X-Swiftarr-Client`: An ID string of the client application. Could be just the name or also include a build number. For example, in the Android app I'm doing `X-Swiftarr-Client: Tricordarr 2024.0`

`X-Swiftarr-User`: If the request is authenticated, also include the users UUID string. Example: `X-Swiftarr-User: abc123-4565-whatever`

These headers will get picked up by the HTTP ingress router and allow us to generate metrics. No functionality is dependent on these headers. If Kraken could honor these too that'd be cool (but not required).

**Comment by challfry** [comment]
Done.
