### ISSUE TITLE
Forums - APP CRASH: Crash when tapping on Like in All Forums

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#9]
If user is not logged in, and taps the heart icon in the All Forums spoke the app crashes 
`2020-01-25 14:43:48.854956-0800 Kraken[86196:1920598] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Receiver (<Kraken.ForumsRootViewController: 0x7fda3f82ac00>) has no segue with identifier 'ModalLogin''
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fe5e8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ea4aac5 objc_exception_throw + 48
	2   UIKitCore                           0x000000011c2b62b3 -[UIViewController shouldPerformSegueWithIdentifier:sender:] + 0
	3   Kraken                              0x000000010cf9fc66 $s6Kraken28BaseCollectionViewControllerC07performA5Segue_6senderyAA011GlobalKnownG0O_ypSgtF + 1382
	4   Kraken                              0x000000010ce6cc12 $s6Kraken16ForumsThreadCellC17favoriteButtonHityyF + 1234
	5   Kraken                              0x000000010ce6cdfb $s6Kraken16ForumsThreadCellC17favoriteButtonHityyFTo + 43
	6   UIKitCore                           0x000000011c8b7624 -[UIApplication sendAction:to:from:forEvent:] + 83
	7   UIKitCore                           0x000000011c30c8d5 -[UIControl sendAction:to:forEvent:] + 67
	8   UIKitCore                           0x000000011c30cbf2 -[UIControl _sendActionsForEvents:withEvent:] + 450
	9   UIKitCore                           0x000000011c30bba8 -[UIControl touchesEnded:withEvent:] + 583
	10  UIKitCore                           0x000000011c8f04e6 -[UIWindow _sendTouchesForEvent:] + 2547
	11  UIKitCore                           0x000000011c8f1bca -[UIWindow sendEvent:] + 4079
	12  UIKitCore                           0x000000011c8d030e -[UIApplication sendEvent:] + 356
	13  UIKitCore                           0x000000011c9a02b3 __dispatchPreprocessedEventFromEventQueue + 3232
	14  UIKitCore                           0x000000011c9a2bd9 __handleEventQueueInternal + 5911
	15  CoreFoundation                      0x000000010fdc5db1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x000000010fdc5633 __CFRunLoopDoSources0 + 243
	17  CoreFoundation                      0x000000010fdbfcef __CFRunLoopRun + 1231
	18  CoreFoundation                      0x000000010fdbf4d2 CFRunLoopRunSpecific + 626
	19  GraphicsServices                    0x0000000115d392fe GSEventRunModal + 65
	20  UIKitCore                           0x000000011c8b5fc2 UIApplicationMain + 140
	21  Kraken                              0x000000010d002a6b main + 75
	22  libdyld.dylib                       0x000000011699b541 start + 1
	23  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

BaseCollectionViewController line 404?

**Comment by challfry** [comment]
The app was trying to show the login panel, but thanks to the way UISegues work it can't do that because the forum VC didn't have a segue to the login VC. Fixed now.
